spring:
  jpa:
    open-in-view: false
  application:
    name: Client-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    schemas: clients_system
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
